name: Build JOSS paper

on:
  push:
    paths:
      - paper.md
      - paper.bib
      - .github/workflows/draft-pdf.yml
  pull_request:
    paths:
      - paper.md
      - paper.bib

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper.md
      - uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf
